### PR TITLE
Review estimate_oc

### PR DESCRIPTION
**Pull request by Pakillo**
I have fully revised and refactored "transform_om_oc" (now called "estimate_oc") #26 

Pending tasks:
- Revise and improve documentation
- Fix Kaufmann et al 2011 equation for Mangroves (looks wrong)
- Decide on log vs lognormal model
- Using ggplot or base plots in the package?
- Write tests

### CODE REVIEW

**Comment by Pakillo** [comment]
Hi, 

re: lm(log) vs lognormal glm, see comparisons here #28 

I'd stick with log(lm) by now. Once we have all settled (including tests), we can switch to a lognormal glm, probably using VGAM.

**Comment by Pakillo** [comment]
So, please @NPJuncal revise the Kaufmann equation when you can, and then I think this can be merged.
I hope any of you can revise the documentation and write tests for this function.
Thanks

**Comment by NPJuncal** [comment]
Hi! Sorry it took me this long to come back here.
The Kaufmann equation is correct, but it does not perform well with low organic matter concentration samples, like the data example. However, is the only published equation for mangrove soils that I known about.
I will add a warning, if the sample has less than xx% of organic matter.
I think we can keep the log(lm) for the first version of the package, so we can focus on finishing the other functions.
I will take care of the documentation and try writing tests (will let you know if I need help with this).
About ggplot or R base for the plot, the test_extrapolation function also uses ggplot, and the plot is quite complicated. I will keep ggplot as a dependency of the package (I think it is pretty well maintained and robust, right?). 

Pending tasks:

Revise and improve documentation (Nerea)
Write tests (Nerea)
Kaufmann equation warning (Nerea)

Thanks a lot @Pakillo and @Julenasti!

**Comment by NPJuncal** [comment]
I think that now the function do not check if there are more than 10 samples with both OM and OC before fiting the models.... I have to check and rewritte and add if needed.

**Pull request merged**
